# typed: false
# frozen_string_literal: true

# Auto-generated by .github/workflows/homebrew-bump.yaml — do not
# hand-edit in the tap repo. Source of truth lives in
# drewcarlson/bwx-cli at packaging/homebrew/bwx-cli.rb.
class BwxCli < Formula
  desc "Unofficial Bitwarden CLI with first-class macOS support"
  homepage "https://github.com/drewcarlson/bwx-cli"
  version "__VERSION__"
  license "MIT"

  # Linux users need pinentry for the master-password UI; macOS uses
  # the bundled osascript dialog so it's optional there.
  on_linux do
    depends_on "pinentry"
  end

  on_macos do
    on_arm do
      url "https://github.com/drewcarlson/bwx-cli/releases/download/v#{version}/bwx-cli-#{version}-aarch64-apple-darwin.tar.gz"
      sha256 "__SHA256_AARCH64_APPLE_DARWIN__"
    end
    on_intel do
      url "https://github.com/drewcarlson/bwx-cli/releases/download/v#{version}/bwx-cli-#{version}-x86_64-apple-darwin.tar.gz"
      sha256 "__SHA256_X86_64_APPLE_DARWIN__"
    end
  end

  on_linux do
    on_arm do
      url "https://github.com/drewcarlson/bwx-cli/releases/download/v#{version}/bwx-cli-#{version}-aarch64-unknown-linux-musl.tar.gz"
      sha256 "__SHA256_AARCH64_UNKNOWN_LINUX_MUSL__"
    end
    on_intel do
      url "https://github.com/drewcarlson/bwx-cli/releases/download/v#{version}/bwx-cli-#{version}-x86_64-unknown-linux-musl.tar.gz"
      sha256 "__SHA256_X86_64_UNKNOWN_LINUX_MUSL__"
    end
  end

  def install
    bin.install "bwx", "bwx-agent"
    bash_completion.install "completion/bash" => "bwx"
    zsh_completion.install "completion/zsh" => "_bwx"
    fish_completion.install "completion/fish" => "bwx.fish"
    doc.install "README.md", "CHANGELOG.md"
  end

  test do
    assert_match(/\A(bwx )?\d+\.\d+\.\d+/, shell_output("#{bin}/bwx --version"))
    assert_match "Touch ID", shell_output("#{bin}/bwx help touchid")
  end
end
